### ISSUE TITLE
Donation Link?

### ISSUE THREAD

**Issue by BlackSheepBoy69** [v-atamanenko/deadspace-vita#1]
.

**Comment by v-atamanenko** [comment]
Added "Sponsor" button. Thanks.
<img width="909" alt="image" src="https://user-images.githubusercontent.com/11796486/198837622-e15ff711-3b77-4f4b-a4cf-e8cf24b919bc.png">

**Comment by BlackSheepBoy69** [comment]
Which is better, ex: which one has less fees to you if someone did a big donation, patreon or paypal?

**Comment by BlackSheepBoy69** [comment]
Ignore that last message for a second, my card is glitching up...

**Comment by BlackSheepBoy69** [comment]
If you need money, there is also a bounty for flash player vita

https://github.com/vita-nuova/bounties/issues/90

Considering the programming language "Rust" was just made available for Vita and the fact that "Ruffle" is coded in rust, it might be a good bounty for you? If you checked the comments, we have already discussed and said porting Ruffle would be an acceptable solution to the bounty.

I would have posted this on your patreon but when I went to give $$$ my card is glitching up with no explanation (there and paypal)
