### ISSUE TITLE
Cant get the game to properly run - constantly encountering error C2-12828-1

### ISSUE THREAD

**Issue by LeetyBOI** [v-atamanenko/deadspace-vita#10]
Really excited that you have managed to release these long awaited port I have a very great nostalgic memories from playing it more than a decade ago :), but unfortunately it seems I cannot get it running at all.

-followed the set-up instructions and installed the data files as described.
-successfully Verified that my build is exactly the correct one using sha1sum.
-I have libshacccg.suprx in the ur0:/data/ + kubridge.skprx (version 0,3) & Repatch_ex.skprx in my ur0:tai folder and in my config.txt under *KERNEL.
-after encountering error C2-12828-1 when trying to boot the game, i have disabled Repatch_ex.skprx , placed FD_FIX in my ur0:tai and in my config.txt under *KERNEL and restarted my VITA console. yet the game still wont boot.
-installed the older 1.1 & 1.0 versions, but again couldn't get pass the boot screen and encountered error C2-12828-1 yet again.  
-Tried to disable all my "optional plugins" in my config.txt file , than rebooted the console and tried to boot the game again - still unsuccessful.
-Uninstalled the game and reinstalled it - again without luck and again error C2-12828-1 popped.

attaching crash dumps + my config.txt file :
[Dead space vita crash.zip](https://github.com/v-atamanenko/deadspace-vita/files/10298749/Dead.space.vita.crash.zip)

I will gladly appreciate your help in trying to determine what else can I do in order to try and get the game running.
Thanks a lot for your great work!

**Comment by v-atamanenko** [comment]
@LeetyBOI sorry for the late reply. Only three possible reasons I can think of:
1) You have ux0:/tai/config.txt in addition to ur0:/tai/config.txt and thus it's being used instead of the correct ur0: one.
2) kubridge is not v0.3+, i.e. you might have mis-copied something.
3) The ioplus plugin is interfering. Try disabling that as well.

Um, also, what firmware version are you using and do you have enso?

**Comment by LeetyBOI** [comment]
Hi, thanks for your reply:
1.Not the case, I have  single tai folder in ur0:/ only.
2. Tried to delete and copy kubridge v0.3 again, didn't help unfortunately.
3. Tried to disable ioplus plugin too, unfortunately didn't help as well.

-My ps vita version is 3.65 , and i have enso as well.
-Tried and failed to boot every version of the Game from 1.0 to 1.3

**Comment by EbanxJoe** [comment]
Tô quase com o mesmo problema, o vpk só está me pedindo o arquivo: lib/armeabi/libEAMGameDeadSpace.so e não sei onde consigo isso.

**Comment by schrammalama** [comment]
I am having the same issue

**Comment by v-atamanenko** [comment]
Can't reproduce
