### ISSUE TITLE
DLCs

### ISSUE THREAD

**Issue by r3sus** [v-atamanenko/deadspace-vita#13]
Hey, thanks for the project!
Not a Vita user, but interested to get DLCs into Android version. 
- settings
There's `settings.sb` file that is used on iOS to unlock 'em: [base64](https://gist.github.com/r3sus/5fa35ad020ad75ef1df82b88efbf3f53).
Applied on Android, it creates new empty save slot, changes the suit and breaks the text as side effect: [image](https://i.imgur.com/WVUnqWA.png).
- maps swap
some maps might be swapped successfully (w/no crash) i.e. with the first one. But that doesn't works with survivals. Might be related to missing assets tho, that need to be copied as well.
- BlackBerry
version has DLCs as well. The contents are 14 Mb `.so` and assets similar to iOS. [^1] 
- symbols 
the later game version libs have more symbols related to debug menu's. Just making them work would be great, but also there might be something to setting the map directly. 
[^2] 
[^1]: available in contents of zip [here](https://archive.org/details/files-for-the-ultimate-play-book-guide); might be installed in simulator.
[^2]: a side note: there's WIP iOS emulator - touchHLE - with Android support PR'd.

**Comment by RinMaru** [comment]
> Hey, thanks for the project! Not a Vita user, but interested to get DLCs into Android version.
> 
> * settings
>   There's `settings.sb` file that is used on iOS to unlock 'em: [base64](https://gist.github.com/r3sus/5fa35ad020ad75ef1df82b88efbf3f53).
>   Applied on Android, it creates new empty save slot, changes the suit and breaks the text as side effect: [image](https://i.imgur.com/WVUnqWA.png).
> * maps swap
>   some maps might be swapped successfully (w/no crash) i.e. with the first one. But that doesn't works with survivals. Might be related to missing assets tho, that need to be copied as well.
> * BlackBerry
>   version has DLCs as well. The contents are 14 Mb `.so` and assets similar to iOS. [1](#user-content-fn-1-3268efd654302e52d808f943dc47e134)
> * symbols
>   the later game version libs have more symbols related to debug menu's. Just making them work would be great, but also there might be something to setting the map directly.
>   [2](#user-content-fn-2-3268efd654302e52d808f943dc47e134)
> 
> ## Footnotes
> 1. available in contents of zip [here](https://archive.org/details/files-for-the-ultimate-play-book-guide); might be installed in simulator. [↩](#user-content-fnref-1-3268efd654302e52d808f943dc47e134)
> 2. a side note: there's WIP iOS emulator - touchHLE - with Android support PR'd. [↩](#user-content-fnref-2-3268efd654302e52d808f943dc47e134)

Im sure if your willing to work with him he may consider it on a sidenote thanks for mentioning TouchHLE i never heard of it but ive been hoping for such a project

**Comment by v-atamanenko** [comment]
Sorry, not interested in this. Also, as cursed as the .so we're using currently is, any extra manipulation with it is a road to nowhere.

You can try to contact the PG Team, they're doing mods for a lot of Vita games and Android->Vita ports, maybe they would be interested.

**Comment by r3sus** [comment]
No problem and thank you!
