### ISSUE TITLE
Recompile to APK for android

### ISSUE THREAD

**Issue by ltlwet20** [v-atamanenko/deadspace-vita#14]
Would it be possible to use this to recompile this back into and android app to play on an Android device with a controller?

**Comment by v-atamanenko** [comment]
it is possible, all you need to do is decompile classes.dex and replicate the behavior of [controls.c](https://github.com/v-atamanenko/deadspace-vita/blob/3eaa3c4b8a0201eec746f7676e0bddcffc5d5638/loader/reimpl/controls.c) in Java, replacing the old handling of xperia play controls.

however personally I never did anything like that and don't even own android devices, so I won't be of help with the practical part of this. but any android "romhacker" should be able to do it
