### ISSUE TITLE
Left / right strafe on left analog for PSTV

### ISSUE THREAD

**Issue by garymohan** [v-atamanenko/deadspace-vita#2]
Is there a way of configuring reVita which provides left / right strafing on the left analog stick on a PlayStation TV?

**Comment by v-atamanenko** [comment]
Not sure what you mean. Doesn't it work like that already? I certainly see left/right strafe when I move left stick left/right.

**Comment by garymohan** [comment]
On my PSTV, the left stick moves back / forward OK.  Left / right strafe is missing.

**Comment by DigiD2** [comment]
> On my PSTV, the left stick moves back / forward OK. Left / right strafe is missing.

Im also on PSTV and it works just fine strafing using the analog stick. Try turning off reVita because you might have something mixed up or another plugin could be causing the issue as well.

**Comment by garymohan** [comment]
Yeah, it's working better with the plugin switched off.

**Comment by v-atamanenko** [comment]
Alright, closing the issue then.
