### ISSUE TITLE
Some issue with plugin...

### ISSUE THREAD

**Issue by chronoss09** [v-atamanenko/deadspace-vita#3]
My Test witch only plugins and all version of Dead Space :

Kubridge v3 + fd_fix
Dead Space v1.0 : Work
Dead Space v1.1 : freeze at boot
Dead Space v1.2 : freeze at boot

Kubridge v3 + fd_fix + rePatch v2.71
Dead Space v1.0 : Work
Dead Space v1.1 : freeze at boot
Dead Space v1.2 : freeze at boot

Kubridge v3 + fd_fix + rePatch v3.0
Dead Space v1.0 : Work
Dead Space v1.1 : freeze at boot
Dead Space v1.2 : freeze at boot

Kubridge v3 + fd_fix + rePatch_ex
Dead Space v1.0 : Work
Dead Space v1.1 : freeze at boot
Dead Space v1.2 : freeze at boot

Kubridge v3 +  rePatch v2.71
Dead Space v1.0 : Work
Dead Space v1.1 : freeze at boot
Dead Space v1.2 : freeze at boot

Kubridge v3 +  rePatch v3.0
Dead Space v1.0 : Work
Dead Space v1.1 : freeze at boot
Dead Space v1.2 : freeze at boot

Kubridge v3 +  rePatch_ex
Dead Space v1.0 : Work
Dead Space v1.1 : freeze at boot
Dead Space v1.2 : freeze at boot

**Comment by v-atamanenko** [comment]
fd_fix / repatch don't influence startup at all. Can you please record a video of this freeze? with any combination of mentioned plugins

**Comment by chronoss09** [comment]
Here my vidéo : https://youtu.be/zXT20doT7GY

**Comment by v-atamanenko** [comment]
Umm why do you close it so fast though? Wait some more. About a minute.

**Comment by Holdenw4ve** [comment]
I have the very same issue, I've been trying to make it work for 5+ hours but no luck :(
(Yesterday it was working nicely on v1.1, all this happened after installing v1.2)

**Comment by v-atamanenko** [comment]
@Holdenw4ve please record a video of the issue, but make sure to wait at least 90 seconds since starting the app.

**Comment by Holdenw4ve** [comment]
@v-atamanenko here's my video, sorry for the late reply!

https://youtu.be/_pHd4IfrSk0

In my case, the game crashes a few seconds after starting it, been trying to re-install fd_fix and kubridge v.03 but doesn't really help

**Comment by v-atamanenko** [comment]
@Holdenw4ve huh. Interesting. And you say v1.0 works? Can you send me the crash dump?

**Comment by Holdenw4ve** [comment]
In my case, any version is working anymore!
I've been playing since the first day of uploading, and everything has been nice, no crashes, no visual problems, just a few audio issues which were fixed by closing the game and starting it again.
Today I installed the new update and haven't been able to run any version anymore, I thought reinstalling the older versions would work, but I just tried that while uploading the video and I haven't got any luck yet...

Sure thing, how can I send you the crash dump?

**Comment by v-atamanenko** [comment]
find newest file which name starts with "psp2dmp" in ux0:data, send it to me

**Comment by Holdenw4ve** [comment]
Here it is (v1.2)
https://www.mediafire.com/file/81pm7xw0gadjklj/psp2core-1667781209-0x00007a2d47-eboot.bin.psp2dmp/file

(Still new to GitHub, sorry for my ignorance)

**Comment by chronoss09** [comment]
Yes you right, the boot take more time from v1 to v1.2
v1.0 : take 25.77s to see the EA logo after the black screen
v1.1 : take 26.70 to see the EA logo and no black screen
v12 : take 26.05 to see the EA logo and no black screen

I have no playing the game but test only the boot for now to see if it work or not... and here are all my crash dump file during my test...
https://www.mediafire.com/folder/0qwuwdywx2hzv/Dead_Space

**Comment by ONElua** [comment]
And you config.txt

**Comment by chronoss09** [comment]
This is my best config file that i use with all game and with this, DS don't work, i give a error dump too...

https://www.mediafire.com/folder/waivg7xdzsz6xk6,iazjj9fz34dnxcm/shared

**Comment by v-atamanenko** [comment]
Sorry, I can not debug this. If older version works for you, use that.
