### ISSUE TITLE
Deadspace chapter 7 g jump

### ISSUE THREAD

**Issue by everonerock** [v-atamanenko/deadspace-vita#4]
The game deadspace is awesome but been stuck on that level were you have to jump but it says to shake down and up but still nothing can you explain what needs to be done.thanks

**Comment by v-atamanenko** [comment]
From [README](https://github.com/v-atamanenko/deadspace-vita#readme):
<img width="837" alt="зображення" src="https://user-images.githubusercontent.com/11796486/201103348-3f1b6214-4a89-4d64-a71e-0c0ff643fcf5.png">

**Comment by RinMaru** [comment]
> From [README](https://github.com/v-atamanenko/deadspace-vita#readme): <img alt="зображення" width="837" src="https://user-images.githubusercontent.com/11796486/201103348-3f1b6214-4a89-4d64-a71e-0c0ff643fcf5.png">

even after trying what is explained here i had to end up holding the vita in one hand waving it side to side softly. moving it too fast in any direction or manor didnt give results

**Comment by everonerock** [comment]
> From [README](https://github.com/v-atamanenko/deadspace-vita#readme): <img alt="зображення" width="837" src="https://user-images.githubusercontent.com/11796486/201103348-3f1b6214-4a89-4d64-a71e-0c0ff643fcf5.png">

Tryed that still at same area other people having same issue any suggestions

**Comment by v-atamanenko** [comment]
If nothing helps from the advices here, maybe the accelerometer on your Vita is faulty. I have a plan to allow alternate (button) binding for accelerometer actions in the next version. Until then, don't think there's anything we can do, sorry.

**Comment by v-atamanenko** [comment]
@everonerock v1.3 with acceletometer actions rebind is released, if that's still relevant to you.
