### ISSUE TITLE
Movement/Left Analog Stick Sensitivity

### ISSUE THREAD

**Issue by Akelaphobia** [v-atamanenko/deadspace-vita#5]
Is it possible to adjust the left analog stick's sensitivity so walking is easier? Currently you have to just barely push the analog stick to walk, maybe 10% pressure on the stick, otherwise any more will make you run. I'd like if instead I could push the left analog stick about halfway in before I start running.

Also thank you very much for this port! I was always hoping this'd get ported to PC or something since touch controls are just.. not fun imo.

**Comment by v-atamanenko** [comment]
I'll look into it

**Comment by v-atamanenko** [comment]
Unfortunately can not be fixed. Well, at least I failed to. It's either (almost) not walking and all running, or awful bugs with random movements.
