### ISSUE TITLE
Plasma Gun turns vertical/horizontal every few seconds w/out me turning screen

### ISSUE THREAD

**Issue by TaMpAbLaCk** [v-atamanenko/deadspace-vita#6]
Plasma Gun turns vertical/horizontal every few seconds w/out me turning screen. Is there any fix to this? I mean it is still playable but sux during a fight when gun is switching 180° as harder to keep aim on point. Tyvm

**Comment by RinMaru** [comment]
> Plasma Gun turns vertical/horizontal every few seconds w/out me turning screen. Is there any fix to this? I mean it is still playable but sux during a fight when gun is switching 180° as harder to keep aim on point. Tyvm

Sounds like your gyro might be showing its age. Had no such issue myself

**Comment by TaMpAbLaCk** [comment]
It only happens when hit left shoulder button and hold it for aim it switches 180° not every time but a lot, but when I tilt screen it switches 180° like it supposed to. When standing still and press left shoulder button to aim it seems to switch 180° horizontal to vertical often and less if walking with left shoulder button held down sometimes it won't do it but usually does it
I'm running plugin overclock at 444. Should I turn that off? Is there any fix to the gyro other than replacing if that is even possible? Thanks.

**Comment by TaMpAbLaCk** [comment]
Tyvm

**Comment by TaMpAbLaCk** [comment]
Last question do I change the accelerometer binding to dpad in game or with that 1 plugin that u can change all buttons forgot name of it.

**Comment by v-atamanenko** [comment]
@TaMpAbLaCk v1.3 with acceletometer actions rebind is released, if that's still relevant to you.
