### ISSUE TITLE
Implement accelerometer binding to dpad up

### ISSUE THREAD

**Issue by v-atamanenko** [v-atamanenko/deadspace-vita#7]

**Comment by v-atamanenko** [comment]
Should solve #4 and #6

**Comment by Poin59** [comment]
+1 UP

**Comment by TaMpAbLaCk** [comment]
Hey Poin59, how to I remap the accelerometer to Dpad up? Use the RemaPSVplugin or is there something in Dead Space to remap already?

**Comment by TaMpAbLaCk** [comment]
> +1 UP

Hey Poin59, how to I remap the accelerometer to Dpad up? Use the RemaPSVplugin or is there something in Dead Space to remap already?

**Comment by TaMpAbLaCk** [comment]
> _No description provided._
I've never recapped the buttons before do I 
remap the accelerometer to Dpad up by using the RemaPSVplugin or is there something in Dead Space to remap already it already? Tyvm for any info

**Comment by TaMpAbLaCk** [comment]
> Should solve #4 and #6

How do I re-map the accelerometer to Dpad up? Use the RemaPSVplugin or is there something in Dead Space options to remap it already or a different plugin? Sorry I've never re-mpped any buttons before much less the accelerometer. Tyvm for any info!

**Comment by v-atamanenko** [comment]
@Poin59 v1.3 with acceletometer actions rebind is released, if that's still relevant to you.
