### ISSUE TITLE
after a few minutes of play there's no sound

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [v-atamanenko/deadspace-vita#8]
after a few minutes of play, likely 3-4mins the game goes mute.
i'm using the latest 1.2 version of the vpk.
i'm gonna try out the older versions too but pls have a look on this problem.

**Comment by RinMaru** [comment]
> after a few minutes of play, likely 3-4mins the game goes mute. i'm using the latest 1.2 version of the vpk. i'm gonna try out the older versions too but pls have a look on this problem.

it has to be the experia version all other versions have issues

**Comment by TheOneEyedGrimReaper** [comment]
> > after a few minutes of play, likely 3-4mins the game goes mute. i'm using the latest 1.2 version of the vpk. i'm gonna try out the older versions too but pls have a look on this problem.
> 
> it has to be the experia version all other versions have issues

I have a version i found it on reddit, i don't know if it's the xperia play version or not, everything is working fine just the sound goes mute after a few minutes of play.

Can you give me a link for the datafiles you're using?

**Comment by RinMaru** [comment]
> > > after a few minutes of play, likely 3-4mins the game goes mute. i'm using the latest 1.2 version of the vpk. i'm gonna try out the older versions too but pls have a look on this problem.
> > 
> > 
> > it has to be the experia version all other versions have issues
> 
> I have a version i found it on reddit, i don't know if it's the xperia play version or not, everything is working fine just the sound goes mute after a few minutes of play.
> 
> Can you give me a link for the datafiles you're using?

I cant since doing so would get the dev in legal trouble but i will say there are two links one is with enhanced textures from ios and one thats the base game. install the base game first and then install the enhanced one but remove the sound folder from the enhanced one so it doesnt overwrite sound files of the base game because it will cut off sound

**Comment by v-atamanenko** [comment]
@TheOneEyedGrimReaper I'll send here a test build today that should have the issue fixed

**Comment by v-atamanenko** [comment]
@TheOneEyedGrimReaper may be bettern in the v1.3 released today, you may try. If not, there's nothing I can do more, unfortunately. No audio cut offs for me personally.

**Comment by RinMaru** [comment]
its fixed just cuts off f you die enough times

**Comment by v-atamanenko** [comment]
Good enough I guess, thanks for the feedback @RinMaru
