### ISSUE TITLE
Vita TV + DS4 Gyroscope

### ISSUE THREAD

**Issue by voradori** [v-atamanenko/deadspace-vita#9]
Trying to play on Vita TV using Dualshock 4
Can't rotate weapon with gyroscope, making the game unplayable

Please add gyro support to ds4 or assign laser rotation on some button

**Comment by v-atamanenko** [comment]
@voradori v1.3 just released with an option to rebind accelerometer actions to D-Pad Up. Alternatively, install [DSMotion](https://github.com/OperationNT414C/DSMotion/releases) and use the gamepad's built-in gyroscope.
